# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='apellidos',
            new_name='apellido',
        ),
    ]
